library(ggplot2)
iPS = read.delim("~/Documents/Research/results/iPS/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
ADM.D0 = read.delim("~/Documents/Research/results/ADM.D0/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
ADM.D4 = read.delim("~/Documents/Research/results/ADM.D4/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
ISM.D0 = read.delim("~/Documents/Research/results/ISM.D0/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
ISM.D4 = read.delim("~/Documents/Research/results/ISM.D4/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
S1 = read.delim("~/Documents/Research/results/S1/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
S2 = read.delim("~/Documents/Research/results/S2/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")
S3 = read.delim("~/Documents/Research/results/S3/ToFU/iso.collapsed.rep.fq.sorted.sam.matchAnnot.txt.parsed.txt")

iPS = na.omit(iPS)
S1 = na.omit(S1)
S2 = na.omit(S2)
S3 = na.omit(S3)
ISM.D0 = na.omit(ISM.D0)
ISM.D4 = na.omit(ISM.D4)
ADM.D0 = na.omit(ADM.D0)
ADM.D4 = na.omit(ADM.D4)

gene.ADM.D0 = unique(ADM.D0$refgene)
gene.ADM.D4 = unique(ADM.D4$refgene)
gene.ISM.D0 = unique(ISM.D0$refgene)
gene.ISM.D4 = unique(ISM.D4$refgene)
gene.S1 = unique(S1$refgene)
gene.S2 = unique(S2$refgene)
gene.S3 = unique(S3$refgene)
gene.iPS = unique(iPS$refgene)

#### genes with different isoform numbers

iPSfreq = table(iPS$refgene)
iPSfreq = as.data.frame(iPSfreq)
over1 = subset(iPSfreq, Freq>=5)
gene.iPS = unique(over1$Var1)

S1freq = table(S1$refgene)
S1freq = as.data.frame(S1freq)
over1 = subset(S1freq, Freq>=5)
gene.S1 = unique(over1$Var1)

S2freq = table(S2$refgene)
S2freq = as.data.frame(S2freq)
over1 = subset(S2freq, Freq>=5)
gene.S2 = unique(over1$Var1)

S3freq = table(S3$refgene)
S3freq = as.data.frame(S3freq)
over1 = subset(S3freq, Freq>=5)
gene.S3 = unique(over1$Var1)

ISM.D0freq = table(ISM.D0$refgene)
ISM.D0freq = as.data.frame(ISM.D0freq)
over1 = subset(ISM.D0freq, Freq>=5)
gene.ISM.D0 = unique(over1$Var1)

ISM.D4freq = table(ISM.D4$refgene)
ISM.D4freq = as.data.frame(ISM.D4freq)
over1 = subset(ISM.D4freq, Freq>=5)
gene.ISM.D4 = unique(over1$Var1)

ADM.D0freq = table(ADM.D0$refgene)
ADM.D0freq = as.data.frame(ADM.D0freq)
over1 = subset(ADM.D0freq, Freq>=5)
gene.ADM.D0 = unique(over1$Var1)

ADM.D4freq = table(ADM.D4$refgene)
ADM.D4freq = as.data.frame(ADM.D4freq)
over1 = subset(ADM.D4freq, Freq>=5)
gene.ADM.D4 = unique(over1$Var1)

length(intersect(gene.iPS,gene.S1))/length(union(gene.iPS,gene.S1))
length(intersect(gene.iPS,gene.S2))/length(union(gene.iPS,gene.S2))
length(intersect(gene.iPS,gene.S3))/length(union(gene.iPS,gene.S3))
length(intersect(gene.iPS,gene.ISM.D0))/length(union(gene.iPS,gene.ISM.D0))
length(intersect(gene.iPS,gene.ISM.D4))/length(union(gene.iPS,gene.ISM.D4))
length(intersect(gene.iPS,gene.ADM.D0))/length(union(gene.iPS,gene.ADM.D0))
length(intersect(gene.iPS,gene.ADM.D4))/length(union(gene.iPS,gene.ADM.D4))
length(intersect(gene.S1,gene.S2))/length(union(gene.S1,gene.S2))
length(intersect(gene.S1,gene.S3))/length(union(gene.S1,gene.S3))
length(intersect(gene.S1,gene.ISM.D0))/length(union(gene.S1,gene.ISM.D0))
length(intersect(gene.S1,gene.ISM.D4))/length(union(gene.S1,gene.ISM.D4))
length(intersect(gene.S1,gene.ADM.D0))/length(union(gene.S1,gene.ADM.D0))
length(intersect(gene.S1,gene.ADM.D4))/length(union(gene.S1,gene.ADM.D4))
length(intersect(gene.S2,gene.S3))/length(union(gene.S2,gene.S3))
length(intersect(gene.S2,gene.ISM.D0))/length(union(gene.S2,gene.ISM.D0))
length(intersect(gene.S2,gene.ISM.D4))/length(union(gene.S2,gene.ISM.D4))
length(intersect(gene.S2,gene.ADM.D0))/length(union(gene.S2,gene.ADM.D0))
length(intersect(gene.S2,gene.ADM.D4))/length(union(gene.S2,gene.ADM.D4))
length(intersect(gene.S3,gene.ISM.D0))/length(union(gene.S3,gene.ISM.D0))
length(intersect(gene.S3,gene.ISM.D4))/length(union(gene.S3,gene.ISM.D4))
length(intersect(gene.S3,gene.ADM.D0))/length(union(gene.S3,gene.ADM.D0))
length(intersect(gene.S3,gene.ADM.D4))/length(union(gene.S3,gene.ADM.D4))
length(intersect(gene.ISM.D0,gene.ISM.D4))/length(union(gene.ISM.D0,gene.ISM.D4))
length(intersect(gene.ISM.D0,gene.ADM.D0))/length(union(gene.ISM.D0,gene.ADM.D0))
length(intersect(gene.ISM.D0,gene.ADM.D4))/length(union(gene.ISM.D0,gene.ADM.D4))
length(intersect(gene.ISM.D4,gene.ADM.D0))/length(union(gene.ISM.D4,gene.ADM.D0))
length(intersect(gene.ISM.D4,gene.ADM.D4))/length(union(gene.ISM.D4,gene.ADM.D4))
length(intersect(gene.ADM.D0,gene.ADM.D4))/length(union(gene.ADM.D0,gene.ADM.D4))

